version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finntv_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - finntv_net

  web:
    image: nginx:alpine
    container_name: finntv_web
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - finntv_net

networks:
  finntv_net:
    driver: bridge
